
  # After registering a name on build.snapcraft.io, commit an uncommented line:
  name: prefixer
  version: '1.1.1' # just for humans, typically '1.2+git' or '1.3.2'
  summary: Adds a prefix to all lines of STDOUT. # 79 char long summary
  description: |
    A simple package to add a small output at the beginning of each STDOUT line.

  grade: stable # must be 'stable' to release into candidate/stable channels
  confinement: strict # use 'strict' once you have the right plugs and slots

  parts:
    build:
      plugin: make
  
