
  name: prefixer
  version: '1.1.1'
  summary: Adds a prefix to all lines of STDOUT
  description: |
    A simple package to add a small output at the beginning of each STDOUT line.
  grade: stable
  confinement: strict
  parts:
    build:
      plugin: make
  
